<?php

use Illuminate\Database\Seeder;

class FieldsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('fields')->delete();
        
        \DB::table('fields')->insert(array (
            
            array (
                'type' => 1,
                'name' => 'File Name',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'file_name',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the human-readable file name.',
                'validation_rules' => '',
                'module_id' => 4,
                'order' => 0,
                'editable' => 0,
                'disabled' => 0,
                'hidden' => 1,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
            
            array (
                'type' => 1,
                'name' => 'Mime Type',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'mime_type',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the file mime type.',
                'validation_rules' => NULL,
                'module_id' => 4,
                'order' => 1,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 1,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
            
            array (
                'type' => 10,
                'name' => 'File Size',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'file_size',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the file size.',
                'validation_rules' => NULL,
                'module_id' => 4,
                'order' => 2,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 1,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
            
            array (
                'type' => 1,
                'name' => 'Real Name and Location',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'storage_file_name',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the file real file name and path in the storage.',
                'validation_rules' => NULL,
                'module_id' => 4,
                'order' => 3,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 1,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
            
            array (
                'type' => 10,
                'name' => 'Image Width',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'image_width',
                'virtual_name' => NULL,
                'tooltip_text' => 'If asset is image this is it\'s width in pixels.',
                'validation_rules' => NULL,
                'module_id' => 4,
                'order' => 4,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 1,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
            
            array (
                'type' => 10,
                'name' => 'Image Height',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'image_height',
                'virtual_name' => NULL,
                'tooltip_text' => 'If asset is image this is it\'s height in pixels.',
                'validation_rules' => NULL,
                'module_id' => 4,
                'order' => 5,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 1,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
            
            array (
                'type' => 3,
                'name' => 'File',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => NULL,
                'virtual_name' => 'file',
                'tooltip_text' => 'File for upload',
                'validation_rules' => 'file|required',
                'module_id' => 4,
                'order' => 6,
                'editable' => 0,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 1,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-04-12 12:50:31',
                'updated_at' => '2017-04-12 12:50:31',
            ),
            
            array (
                'type' => 1,
                'name' => 'Title',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'title',
                'virtual_name' => NULL,
                'tooltip_text' => 'The title of the image.',
                'validation_rules' => NULL,
                'module_id' => 4,
                'order' => 7,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 0,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2018-01-22 22:35:09',
                'updated_at' => '2018-01-22 22:35:09',
            ),
            
            array (
                'type' => 1,
                'name' => 'Alt Text',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'alt_text',
                'virtual_name' => NULL,
                'tooltip_text' => 'The alt text of the image.',
                'validation_rules' => NULL,
                'module_id' => 4,
                'order' => 8,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 0,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2018-01-22 22:35:09',
                'updated_at' => '2018-01-22 22:35:09',
            ),
            
            array (
                'type' => 8,
                'name' => 'File Tags',
                'related_module' => 7,
                'relation_name' => 'tags',
                'pivot_table' => NULL,
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'Assigned file tags',
                'validation_rules' => 'exists:file_tags,id',
                'module_id' => 4,
                'order' => 9,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 1,
                'can_create_search_choice' => 1,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-10-07 07:38:15',
                'updated_at' => '2016-10-07 07:38:15',
            ),
            
            array (
                'type' => 1,
                'name' => 'File tag name',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'title',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the human-readable file tag name.',
                'validation_rules' => 'required|string|unique:file_tags,title',
                'module_id' => 7,
                'order' => 0,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 1,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-10-07 07:14:34',
                'updated_at' => '2016-10-07 07:14:34',
            ),
            
            array (
                'type' => 1,
                'name' => 'System tag name',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'system_name',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the tag system name.',
                'validation_rules' => 'unique:file_tags,system_name',
                'module_id' => 7,
                'order' => 1,
                'editable' => 0,
                'disabled' => 0,
                'hidden' => 1,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-10-07 07:14:34',
                'updated_at' => '2016-10-07 07:14:34',
            ),
            
            array (
                'type' => 1,
                'name' => 'Title',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'title',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the gallery item title.',
                'validation_rules' => 'nullable|string',
                'module_id' => 13,
                'order' => 0,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-08-20 16:33:27',
                'updated_at' => '2017-08-20 16:33:27',
            ),
            
            array (
                'type' => 2,
                'name' => 'Description',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'description',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the gallery item description.',
                'validation_rules' => 'nullable|string',
                'module_id' => 13,
                'order' => 1,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-08-20 16:33:27',
                'updated_at' => '2017-08-20 16:33:27',
            ),
            
            array (
                'type' => 7,
                'name' => 'Asset',
                'related_module' => 4,
                'relation_name' => 'asset',
                'pivot_table' => NULL,
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'This is asset related to this gallery item',
                'validation_rules' => 'required|integer|exists:assets,id',
                'module_id' => 13,
                'order' => 2,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 1,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-08-20 16:38:43',
                'updated_at' => '2017-08-20 16:42:13',
            ),
            
            array (
                'type' => 1,
                'name' => 'Title',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'title',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the gallery title.',
                'validation_rules' => '',
                'module_id' => 12,
                'order' => 0,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-08-20 16:32:56',
                'updated_at' => '2017-08-20 16:38:43',
            ),
            
            array (
                'type' => 1,
                'name' => 'Name',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'name',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image size name.',
                'validation_rules' => 'required|string',
                'module_id' => 10,
                'order' => 0,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:52:01',
                'updated_at' => '2017-06-13 06:52:01',
            ),
            
            array (
                'type' => 10,
                'name' => 'Width',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'width',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image width.',
                'validation_rules' => 'integer',
                'module_id' => 10,
                'order' => 1,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:52:01',
                'updated_at' => '2017-06-13 06:52:01',
            ),
            
            array (
                'type' => 10,
                'name' => 'Height',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'height',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image height.',
                'validation_rules' => 'integer',
                'module_id' => 10,
                'order' => 2,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:52:01',
                'updated_at' => '2017-06-13 06:52:01',
            ),
            
            array (
                'type' => 4,
                'name' => 'Lock width',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'lock_width',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image lock width.',
                'validation_rules' => 'boolean',
                'module_id' => 10,
                'order' => 3,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:52:01',
                'updated_at' => '2017-06-13 06:52:01',
            ),
            
            array (
                'type' => 4,
                'name' => 'Lock height',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'lock_height',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image lock height.',
                'validation_rules' => 'boolean',
                'module_id' => 10,
                'order' => 4,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:52:01',
                'updated_at' => '2017-06-13 06:52:01',
            ),
            
            array (
                'type' => 10,
                'name' => 'Top X',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'top_x',
                'virtual_name' => NULL,
                'tooltip_text' => 'Top left x position.',
                'validation_rules' => 'integer',
                'module_id' => 9,
                'order' => 0,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:41:12',
                'updated_at' => '2017-06-13 06:41:12',
            ),
            
            array (
                'type' => 10,
                'name' => 'Top Y',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'top_y',
                'virtual_name' => NULL,
                'tooltip_text' => 'Top left y position.',
                'validation_rules' => 'integer',
                'module_id' => 9,
                'order' => 1,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:41:12',
                'updated_at' => '2017-06-13 06:41:12',
            ),
            
            array (
                'type' => 10,
                'name' => 'Width',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'width',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image crop width.',
                'validation_rules' => 'integer',
                'module_id' => 9,
                'order' => 2,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:41:12',
                'updated_at' => '2017-06-13 06:41:12',
            ),
            
            array (
                'type' => 10,
                'name' => 'Height',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'height',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image crop height',
                'validation_rules' => 'integer',
                'module_id' => 9,
                'order' => 3,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:41:12',
                'updated_at' => '2017-06-13 06:41:12',
            ),
            
            array (
                'type' => 7,
                'name' => 'Image',
                'related_module' => 4,
                'relation_name' => 'image',
                'pivot_table' => NULL,
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the original image.',
                'validation_rules' => 'integer',
                'module_id' => 9,
                'order' => 4,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:41:12',
                'updated_at' => '2017-06-13 06:41:12',
            ),
            
            array (
                'type' => 7,
                'name' => 'Image size',
                'related_module' => 10,
                'relation_name' => 'image_size',
                'pivot_table' => NULL,
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the image size.',
                'validation_rules' => 'integer',
                'module_id' => 9,
                'order' => 5,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:55:38',
                'updated_at' => '2017-06-13 06:55:38',
            ),
            
            array (
                'type' => 1,
                'name' => 'Mime Type',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'mime_type',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the file mime type.',
                'validation_rules' => NULL,
                'module_id' => 9,
                'order' => 6,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
            
            array (
                'type' => 10,
                'name' => 'File Size',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'file_size',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the file size.',
                'validation_rules' => NULL,
                'module_id' => 9,
                'order' => 7,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
            
            array (
                'type' => 1,
                'name' => 'Real Name and Location',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'storage_file_name',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the file real file name and path in the storage.',
                'validation_rules' => NULL,
                'module_id' => 9,
                'order' => 8,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
            
            array (
                'type' => 10,
                'name' => 'Image Width',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'image_width',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image width in pixels.',
                'validation_rules' => NULL,
                'module_id' => 9,
                'order' => 9,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
            
            array (
                'type' => 10,
                'name' => 'Image Height',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'image_height',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image height in pixels.',
                'validation_rules' => NULL,
                'module_id' => 9,
                'order' => 10,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
            
            array (
                'type' => 17,
                'name' => 'Resized images',
                'related_module' => 9,
                'relation_name' => 'resized_images',
                'pivot_table' => NULL,
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'Resized images generated for this asset.',
                'validation_rules' => NULL,
                'module_id' => 4,
                'order' => 8,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 1,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => 'id',
                'foreign_key' => 'image',
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:49:50',
                'updated_at' => '2017-06-13 06:49:50',
            ),
            
            array (
                'type' => 1,
                'name' => 'Title',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'title',
                'virtual_name' => NULL,
                'tooltip_text' => 'The invitation status title.',
                'validation_rules' => 'string|required',
                'module_id' => 3,
                'order' => 0,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-08-18 12:18:07',
                'updated_at' => '2016-08-18 12:18:07',
            ),
            
            array (
                'type' => 1,
                'name' => 'System Name',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'system_name',
                'virtual_name' => NULL,
                'tooltip_text' => 'The invitation system status name.',
                'validation_rules' => 'alpha_dash|required|unique:invitation_statuses',
                'module_id' => 3,
                'order' => 1,
                'editable' => 0,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-08-18 12:18:07',
                'updated_at' => '2016-08-18 12:18:07',
            ),
            
            array (
                'type' => 1,
                'name' => 'Email',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'email',
                'virtual_name' => NULL,
                'tooltip_text' => 'A user invitation email.',
                'validation_rules' => 'required_without:csv_file|unique:users,email|max:255',
                'module_id' => 2,
                'order' => 0,
                'editable' => 0,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-08-18 08:10:56',
                'updated_at' => '2016-08-18 08:10:56',
            ),
            
            array (
                'type' => 1,
                'name' => 'Invitation Code',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'invitation_code',
                'virtual_name' => NULL,
                'tooltip_text' => 'A user invitation token.',
                'validation_rules' => NULL,
                'module_id' => 2,
                'order' => 1,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 1,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-08-18 10:04:23',
                'updated_at' => '2016-08-18 10:04:23',
            ),
            
            array (
                'type' => 7,
                'name' => 'Invitation Status',
                'related_module' => 3,
                'relation_name' => 'invitation_status',
                'pivot_table' => NULL,
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'The current status of the invitation.',
                'validation_rules' => 'exists:invitation_statuses,id',
                'module_id' => 2,
                'order' => 2,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2016-08-18 12:35:42',
                'updated_at' => '2016-08-18 12:35:42',
            ),
            
            array (
                'type' => 18,
                'name' => 'First Sent At',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'first_sent',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the date when the invitation was first sent.',
                'validation_rules' => NULL,
                'module_id' => 2,
                'order' => 3,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-08-18 12:43:05',
                'updated_at' => '2016-08-18 12:43:05',
            ),
            
            array (
                'type' => 18,
                'name' => 'Last Resent At',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'resent_at',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the last date when the invitation was resent.',
                'validation_rules' => NULL,
                'module_id' => 2,
                'order' => 4,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-08-18 12:43:05',
                'updated_at' => '2016-08-18 12:43:05',
            ),
            
            array (
                'type' => 15,
                'name' => 'CSV File',
                'related_module' => 4,
                'relation_name' => 'csv_file',
                'pivot_table' => NULL,
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'Upload a file containing email addresses for invitations.',
                'validation_rules' => 'required_without:email|integer',
                'module_id' => 2,
                'order' => 5,
                'editable' => 0,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2016-08-23 16:41:18',
                'updated_at' => '2016-08-23 16:41:18',
            ),
            
            array (
                'type' => 7,
                'name' => 'Default Role',
                'related_module' => 5,
                'relation_name' => 'default_role',
                'pivot_table' => NULL,
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'Role that will be assigned to the user that registers using this invitation.',
                'validation_rules' => 'exists:roles,id',
                'module_id' => 2,
                'order' => 6,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => '2',
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2016-08-18 12:35:42',
                'updated_at' => '2016-08-18 12:35:42',
            ),
            
            array (
                'type' => 1,
                'name' => 'System Name',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'name',
                'virtual_name' => NULL,
                'tooltip_text' => 'The permission system name.',
                'validation_rules' => 'required|unique:permissions',
                'module_id' => 6,
                'order' => 0,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-09-02 12:43:44',
                'updated_at' => '2016-09-02 12:43:44',
            ),
            
            array (
                'type' => 1,
                'name' => 'Title',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'title',
                'virtual_name' => NULL,
                'tooltip_text' => 'The human-readable permission name.',
                'validation_rules' => '',
                'module_id' => 6,
                'order' => 1,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2016-09-02 12:43:44',
                'updated_at' => '2016-09-02 12:43:44',
            ),
            
            array (
                'type' => 1,
                'name' => 'System Name',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'name',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the role system name.',
                'validation_rules' => 'required|unique:roles',
                'module_id' => 5,
                'order' => 0,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-09-02 12:24:28',
                'updated_at' => '2016-09-02 12:24:28',
            ),
            
            array (
                'type' => 1,
                'name' => 'Title',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'title',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the human-readable role name.',
                'validation_rules' => '',
                'module_id' => 5,
                'order' => 1,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-09-02 12:24:28',
                'updated_at' => '2016-09-02 12:24:28',
            ),
            
            array (
                'type' => 24,
                'name' => 'Permissions',
                'related_module' => 6,
                'relation_name' => 'permissions',
                'pivot_table' => 'role_has_permissions',
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'Permissions which are assigned to this role.',
                'validation_rules' => NULL,
                'module_id' => 5,
                'order' => 2,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-09-05 10:28:05',
                'updated_at' => '2016-09-05 10:28:05',
            ),
            
            array (
                'type' => 1,
                'name' => 'Email',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'email',
                'virtual_name' => NULL,
                'tooltip_text' => 'User email will be used as a username. If required, account confirmation will be sent to this email. Email will also be used in the event of recovering a lost password.',
                'validation_rules' => 'required|unique:users,email|max:255',
                'module_id' => 1,
                'order' => 0,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-04-01 09:17:48',
                'updated_at' => '2016-04-01 09:17:48',
            ),
            
            array (
                'type' => 9,
                'name' => 'Password',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'password',
                'virtual_name' => NULL,
                'tooltip_text' => 'User Password.',
            'validation_rules' => 'required|min:8|regex:/^.*(?=.{3,})(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[\\d\\X])(?=.*[!$#%]).*$/',
                'module_id' => 1,
                'order' => 1,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-04-01 09:17:48',
                'updated_at' => '2016-04-01 09:17:48',
            ),
            
            array (
                'type' => 1,
                'name' => 'First Name',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'first_name',
                'virtual_name' => NULL,
                'tooltip_text' => 'User first name.',
                'validation_rules' => 'required|string|min:2',
                'module_id' => 1,
                'order' => 2,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-04-01 09:17:48',
                'updated_at' => '2016-04-01 09:17:48',
            ),
            
            array (
                'type' => 1,
                'name' => 'Last Name',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'last_name',
                'virtual_name' => NULL,
                'tooltip_text' => 'User last name.',
                'validation_rules' => 'required|string|min:2',
                'module_id' => 1,
                'order' => 3,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-04-01 09:17:48',
                'updated_at' => '2016-04-01 09:17:48',
            ),
            
            array (
                'type' => 1,
                'name' => 'Confirmation Code',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'confirmation_code',
                'virtual_name' => NULL,
                'tooltip_text' => 'User confirmation code.',
                'validation_rules' => 'string',
                'module_id' => 1,
                'order' => 4,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 1,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2016-04-01 09:17:48',
                'updated_at' => '2016-04-01 09:17:48',
            ),
            
            array (
                'type' => 4,
                'name' => 'Confirmed',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'confirmed',
                'virtual_name' => NULL,
                'tooltip_text' => 'User confirmation status.',
                'validation_rules' => 'boolean',
                'module_id' => 1,
                'order' => 5,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 1,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2016-04-01 09:17:48',
                'updated_at' => '2016-04-01 09:17:48',
            ),
            
            array (
                'type' => 8,
                'name' => 'Roles',
                'related_module' => 5,
                'relation_name' => 'roles',
                'pivot_table' => 'user_has_roles',
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'Roles which are assigned to this user.',
                'validation_rules' => NULL,
                'module_id' => 1,
                'order' => 6,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2016-09-05 12:50:26',
                'updated_at' => '2016-09-05 12:50:26',
            ),
            
            array (
                'type' => 24,
                'name' => 'Permissions',
                'related_module' => 6,
                'relation_name' => 'permissions',
                'pivot_table' => 'user_has_permissions',
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'Permissions which are assigned to this user.',
                'validation_rules' => NULL,
                'module_id' => 1,
                'order' => 7,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2016-09-05 12:50:26',
                'updated_at' => '2016-09-05 12:50:26',
            ),
            
            array (
                'type' => 15,
                'name' => 'Profile Image',
                'related_module' => 4,
                'relation_name' => 'profile_image',
                'pivot_table' => NULL,
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the user profile image.',
                'validation_rules' => NULL,
                'module_id' => 1,
                'order' => 8,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2016-09-01 06:44:16',
                'updated_at' => '2016-09-01 06:44:16',
            ),
            
            array (
                'type' => 12,
                'name' => 'Password Creation Date',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'password_created_at',
                'virtual_name' => NULL,
                'tooltip_text' => 'Date when the last password was created.',
                'validation_rules' => NULL,
                'module_id' => 1,
                'order' => 9,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 1,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2016-09-29 12:55:25',
                'updated_at' => '2016-09-29 12:55:25',
            ),
            
            array (
                'type' => 12,
                'name' => 'Deletion Date',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'deleted_at',
                'virtual_name' => NULL,
                'tooltip_text' => 'Date when the entry was deleted.',
                'validation_rules' => NULL,
                'module_id' => 1,
                'order' => 10,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 1,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2016-09-29 12:55:25',
                'updated_at' => '2016-09-29 12:55:25',
            ),
            
            array (
                'type' => 1,
                'name' => 'Module',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'module',
                'virtual_name' => NULL,
                'tooltip_text' => 'Data source module.',
                'validation_rules' => 'nullable',
                'module_id' => 8,
                'order' => 0,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 0,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2018-01-10 22:23:31',
                'updated_at' => '2018-01-11 08:18:51',
            ),
            
            array (
                'type' => 1,
                'name' => 'Heading Text',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'heading',
                'virtual_name' => NULL,
                'tooltip_text' => 'The text which will appear in widget heading.',
                'validation_rules' => 'nullable',
                'module_id' => 8,
                'order' => 1,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 0,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2018-01-10 22:23:31',
                'updated_at' => '2018-01-11 08:18:51',
            ),
            
            array (
                'type' => 1,
                'name' => 'Icon',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'icon',
                'virtual_name' => NULL,
                'tooltip_text' => 'The icon which will appear in widget heading.',
                'validation_rules' => 'nullable',
                'module_id' => 8,
                'order' => 2,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 0,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => 'fa fa-circle',
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2018-01-10 22:23:31',
                'updated_at' => '2018-01-11 08:18:51',
            ),
            
            array (
                'type' => 1,
                'name' => 'Theme',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'theme',
                'virtual_name' => NULL,
                'tooltip_text' => 'Widget theme.',
                'validation_rules' => 'required|nullable',
                'module_id' => 8,
                'order' => 3,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 0,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => 'panel-primary',
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2018-01-10 22:23:31',
                'updated_at' => '2018-01-11 08:18:51',
            ),
            
            array (
                'type' => 1,
                'name' => 'Data Refresh Interval',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'refresh_interval',
                'virtual_name' => NULL,
                'tooltip_text' => 'Widget data refresh interval.',
                'validation_rules' => 'integer|nullable',
                'module_id' => 8,
                'order' => 4,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 0,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => '5000',
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2018-01-10 22:23:31',
                'updated_at' => '2018-01-11 08:18:51',
            ),
            
            array (
                'type' => 1,
                'name' => 'Type',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'type',
                'virtual_name' => NULL,
                'tooltip_text' => 'Widget Type',
                'validation_rules' => 'required',
                'module_id' => 8,
                'order' => 6,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 0,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2018-01-10 22:23:31',
                'updated_at' => '2018-01-11 08:18:51',
            ),
            
            array (
                'type' => 2,
                'name' => 'Meta Data',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'meta_data',
                'virtual_name' => NULL,
                'tooltip_text' => 'Data specific to seleted widget type.',
                'validation_rules' => 'nullable',
                'module_id' => 8,
                'order' => 7,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 0,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2018-01-10 22:23:31',
                'updated_at' => '2018-01-11 08:18:51',
            ),
            
            array (
                'type' => 4,
                'name' => 'Private',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'private',
                'virtual_name' => NULL,
                'tooltip_text' => NULL,
                'validation_rules' => NULL,
                'module_id' => 8,
                'order' => 5,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 0,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => '0',
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2018-01-10 22:23:56',
                'updated_at' => '2018-01-11 08:18:51',
            ),
        ));
        
        
    }
}