<?php

use Illuminate\Database\Seeder;

class InitialCoreImageSizesModuleSeeder extends Seeder
{
    public function run()
    {
        \DB::table('modules')->insert(array (
            array (
                'id' => 10,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Image sizes',
                'model_name' => 'ImageSizes',
                'table_name' => 'image_sizes',
                'max_depth' => NULL,
                'anchor_text' => '{{name}}',
                'icon' => 'fa fa-picture-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'created_at' => '2017-06-13 06:52:01',
                'updated_at' => '2017-06-13 06:52:01',
            ),
            array (
                'id' => 9,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Resized Images',
                'model_name' => 'ResizedImages',
                'table_name' => 'resized_images',
                'max_depth' => NULL,
                'anchor_text' => '{{top_x}},{{top_y}} - {{height}},{{width}}',
                'icon' => 'fa fa-picture-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'created_at' => '2017-06-13 06:41:12',
                'updated_at' => '2017-06-13 06:41:12',
            ),
        ));

        // Fields
        \DB::table('fields')->insert(array (
            // image_sizes
            array (
                'type' => 1,
                'name' => 'Name',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'name',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image size name.',
                'validation_rules' => 'required|string',
                'module_id' => 10,
                'order' => 0,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:52:01',
                'updated_at' => '2017-06-13 06:52:01',
            ),

            array (
                'type' => 10,
                'name' => 'Width',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'width',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image width.',
                'validation_rules' => 'integer',
                'module_id' => 10,
                'order' => 1,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:52:01',
                'updated_at' => '2017-06-13 06:52:01',
            ),

            array (
                'type' => 10,
                'name' => 'Height',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'height',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image height.',
                'validation_rules' => 'integer',
                'module_id' => 10,
                'order' => 2,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:52:01',
                'updated_at' => '2017-06-13 06:52:01',
            ),

            array (
                'type' => 4,
                'name' => 'Lock width',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'lock_width',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image lock width.',
                'validation_rules' => 'boolean',
                'module_id' => 10,
                'order' => 3,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:52:01',
                'updated_at' => '2017-06-13 06:52:01',
            ),

            array (
                'type' => 4,
                'name' => 'Lock height',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'lock_height',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image lock height.',
                'validation_rules' => 'boolean',
                'module_id' => 10,
                'order' => 4,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:52:01',
                'updated_at' => '2017-06-13 06:52:01',
            ),

            // resized_images
            array (
                'type' => 10,
                'name' => 'Top X',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'top_x',
                'virtual_name' => NULL,
                'tooltip_text' => 'Top left x position.',
                'validation_rules' => 'integer',
                'module_id' => 9,
                'order' => 0,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:41:12',
                'updated_at' => '2017-06-13 06:41:12',
            ),

            array (
                'type' => 10,
                'name' => 'Top Y',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'top_y',
                'virtual_name' => NULL,
                'tooltip_text' => 'Top left y position.',
                'validation_rules' => 'integer',
                'module_id' => 9,
                'order' => 1,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:41:12',
                'updated_at' => '2017-06-13 06:41:12',
            ),

            array (
                'type' => 10,
                'name' => 'Width',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'width',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image crop width.',
                'validation_rules' => 'integer',
                'module_id' => 9,
                'order' => 2,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:41:12',
                'updated_at' => '2017-06-13 06:41:12',
            ),

            array (
                'type' => 10,
                'name' => 'Height',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'height',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image crop height',
                'validation_rules' => 'integer',
                'module_id' => 9,
                'order' => 3,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:41:12',
                'updated_at' => '2017-06-13 06:41:12',
            ),

            array (
                'type' => 7,
                'name' => 'Image',
                'related_module' => 4,
                'relation_name' => 'image',
                'pivot_table' => NULL,
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the original image.',
                'validation_rules' => 'integer',
                'module_id' => 9,
                'order' => 4,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:41:12',
                'updated_at' => '2017-06-13 06:41:12',
            ),

            array (
                'type' => 7,
                'name' => 'Image size',
                'related_module' => 10,
                'relation_name' => 'image_size',
                'pivot_table' => NULL,
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the image size.',
                'validation_rules' => 'integer',
                'module_id' => 9,
                'order' => 5,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:55:38',
                'updated_at' => '2017-06-13 06:55:38',
            ),

            array (
                'type' => 1,
                'name' => 'Mime Type',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'mime_type',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the file mime type.',
                'validation_rules' => NULL,
                'module_id' => 9,
                'order' => 6,
                'editable' => false,
                'disabled' => true,
                'hidden' => false,
                'is_system' => true,
                'virtual' => false,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),

            array (
                'type' => 10,
                'name' => 'File Size',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'file_size',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the file size.',
                'validation_rules' => NULL,
                'module_id' => 9,
                'order' => 7,
                'editable' => false,
                'disabled' => true,
                'hidden' => false,
                'is_system' => true,
                'virtual' => false,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),

            array (
                'type' => 1,
                'name' => 'Real Name and Location',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'storage_file_name',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the file real file name and path in the storage.',
                'validation_rules' => NULL,
                'module_id' => 9,
                'order' => 8,
                'editable' => false,
                'disabled' => true,
                'hidden' => false,
                'is_system' => true,
                'virtual' => false,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),

            array (
                'type' => 10,
                'name' => 'Image Width',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'image_width',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image width in pixels.',
                'validation_rules' => NULL,
                'module_id' => 9,
                'order' => 9,
                'editable' => false,
                'disabled' => true,
                'hidden' => false,
                'is_system' => true,
                'virtual' => false,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),

            array (
                'type' => 10,
                'name' => 'Image Height',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'image_height',
                'virtual_name' => NULL,
                'tooltip_text' => 'Image height in pixels.',
                'validation_rules' => NULL,
                'module_id' => 9,
                'order' => 10,
                'editable' => false,
                'disabled' => true,
                'hidden' => false,
                'is_system' => true,
                'virtual' => false,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
            // assets relations
            array (
                'type' => 17,
                'name' => 'Resized images',
                'related_module' => 9,
                'relation_name' => 'resized_images',
                'pivot_table' => NULL,
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'Resized images generated for this asset.',
                'validation_rules' => NULL,
                'module_id' => 4,
                'order' => 8,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 1,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'local_key' => 'id',
                'foreign_key' => 'image',
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2017-06-13 06:49:50',
                'updated_at' => '2017-06-13 06:49:50',
            ),
        ));
    }
}
