<?php

use Illuminate\Database\Seeder;

class InitialCoreInvitationsModuleSeeder extends Seeder
{
    public function run()
    {
        // Modules
        \DB::table('modules')->insert(array (
            2 =>
            array (
                'id' => 2,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Invitations',
                'model_name' => 'Invitations',
                'table_name' => 'invitations',
                'anchor_text' => '{{email}}',
                'icon' => 'fa fa-envelope-o',
                'reporting' => false,
                'lazy_loading' => 0,
                'is_system' => true,
                'created_at' => '2016-08-18 08:10:56',
                'updated_at' => '2016-08-18 08:10:56',
            ),
        ));

        // Fields
        \DB::table('fields')->insert(array (
            7 =>
            array (
                'type' => 1,
                'name' => 'Email',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'email',
                'virtual_name' => NULL,
                'tooltip_text' => 'A user invitation email.',
                'validation_rules' => 'required_without:csv_file|unique:users,email|max:255',
                'module_id' => 2,
                'order' => 0,
                'editable' => 0,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-08-18 08:10:56',
                'updated_at' => '2016-08-18 08:10:56',
            ),
            9 =>
            array (
                'type' => 1,
                'name' => 'Invitation Code',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'invitation_code',
                'virtual_name' => NULL,
                'tooltip_text' => 'A user invitation token.',
                'validation_rules' => NULL,
                'module_id' => 2,
                'order' => 1,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 1,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-08-18 10:04:23',
                'updated_at' => '2016-08-18 10:04:23',
            ),
            12 =>
            array (
                'type' => 7,
                'name' => 'Invitation Status',
                'related_module' => 3,
                'relation_name' => 'invitation_status',
                'pivot_table' => NULL,
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'The current status of the invitation.',
                'validation_rules' => 'exists:invitation_statuses,id',
                'module_id' => 2,
                'order' => 2,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2016-08-18 12:35:42',
                'updated_at' => '2016-08-18 12:35:42',
            ),
            13 =>
            array (
                'type' => 18,
                'name' => 'First Sent At',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'first_sent',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the date when the invitation was first sent.',
                'validation_rules' => NULL,
                'module_id' => 2,
                'order' => 3,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-08-18 12:43:05',
                'updated_at' => '2016-08-18 12:43:05',
            ),
            14 =>
            array (
                'type' => 18,
                'name' => 'Last Resent At',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'resent_at',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the last date when the invitation was resent.',
                'validation_rules' => NULL,
                'module_id' => 2,
                'order' => 4,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2016-08-18 12:43:05',
                'updated_at' => '2016-08-18 12:43:05',
            ),
            15 =>
            array (
                'type' => 15,
                'name' => 'CSV File',
                'related_module' => 4,
                'relation_name' => 'csv_file',
                'pivot_table' => NULL,
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'Upload a file containing email addresses for invitations.',
                'validation_rules' => 'required_without:email|integer',
                'module_id' => 2,
                'order' => 5,
                'editable' => 0,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2016-08-23 16:41:18',
                'updated_at' => '2016-08-23 16:41:18',
            ),
            16 =>
            array (
                'type' => 7,
                'name' => 'Default Role',
                'related_module' => 5,
                'relation_name' => 'default_role',
                'pivot_table' => NULL,
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'Role that will be assigned to the user that registers using this invitation.',
                'validation_rules' => 'exists:roles,id',
                'module_id' => 2,
                'order' => 6,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => 2,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2016-08-18 12:35:42',
                'updated_at' => '2016-08-18 12:35:42',
            ),
        ));
    }
}
