<?php

use Illuminate\Database\Seeder;

class InitialCoreAssetsModuleSeeder extends Seeder
{
    public function run()
    {
        \DB::table('modules')->insert(array (
            0 =>
            array (
                'id' => 4,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Assets',
                'model_name' => 'Assets',
                'table_name' => 'assets',
                'anchor_text' => '{{file_name}}',
                'icon' => 'fa fa-file-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
        ));

        // Fields
        \DB::table('fields')->insert(array (
            array (
                'type' => 1,
                'name' => 'File Name',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'file_name',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the human-readable file name.',
                'validation_rules' => '',
                'module_id' => 4,
                'order' => 0,
                'editable' => false,
                'disabled' => false,
                'hidden' => true,
                'is_system' => 1,
                'virtual' => false,
                'lazy_loading' => 0,
                'default' => NULL,
                'nullable' => 0,
                'can_create_search_choice' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
            array (
                'type' => 1,
                'name' => 'Mime Type',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'mime_type',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the file mime type.',
                'validation_rules' => NULL,
                'module_id' => 4,
                'order' => 1,
                'editable' => false,
                'disabled' => true,
                'hidden' => true,
                'is_system' => true,
                'virtual' => false,
                'lazy_loading' => 0,
                'default' => NULL,
                'nullable' => 0,
                'can_create_search_choice' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
            array (
                'type' => 10,
                'name' => 'File Size',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'file_size',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the file size.',
                'validation_rules' => NULL,
                'module_id' => 4,
                'order' => 2,
                'editable' => false,
                'disabled' => true,
                'hidden' => true,
                'is_system' => true,
                'virtual' => false,
                'lazy_loading' => 0,
                'default' => NULL,
                'nullable' => 0,
                'can_create_search_choice' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
            array (
                'type' => 1,
                'name' => 'Real Name and Location',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'storage_file_name',
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the file real file name and path in the storage.',
                'validation_rules' => NULL,
                'module_id' => 4,
                'order' => 3,
                'editable' => false,
                'disabled' => true,
                'hidden' => true,
                'is_system' => true,
                'virtual' => false,
                'lazy_loading' => 0,
                'default' => NULL,
                'nullable' => 0,
                'can_create_search_choice' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
            array (
                'type' => 10,
                'name' => 'Image Width',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'image_width',
                'virtual_name' => NULL,
                'tooltip_text' => 'If asset is image this is it\'s width in pixels.',
                'validation_rules' => NULL,
                'module_id' => 4,
                'order' => 4,
                'editable' => false,
                'disabled' => true,
                'hidden' => true,
                'is_system' => true,
                'virtual' => false,
                'lazy_loading' => 0,
                'default' => NULL,
                'nullable' => 1,
                'can_create_search_choice' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
            array (
                'type' => 10,
                'name' => 'Image Height',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'image_height',
                'virtual_name' => NULL,
                'tooltip_text' => 'If asset is image this is it\'s height in pixels.',
                'validation_rules' => NULL,
                'module_id' => 4,
                'order' => 5,
                'editable' => false,
                'disabled' => true,
                'hidden' => true,
                'is_system' => true,
                'virtual' => false,
                'lazy_loading' => 0,
                'default' => NULL,
                'nullable' => 1,
                'can_create_search_choice' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
            array (
                'type' => 3,
                'name' => 'File',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => NULL,
                'virtual_name' => 'file',
                'tooltip_text' => 'File for upload',
                'validation_rules' => 'file|required',
                'module_id' => 4,
                'order' => 6,
                'editable' => 0,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 1,
                'lazy_loading' => 0,
                'default' => NULL,
                'nullable' => 0,
                'can_create_search_choice' => 0,
                'created_at' => '2017-04-12 12:50:31',
                'updated_at' => '2017-04-12 12:50:31',
            ),
            array (
                'type' => 1,
                'name' => 'Title',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'title',
                'virtual_name' => NULL,
                'tooltip_text' => 'The title of the image.',
                'validation_rules' => NULL,
                'module_id' => 4,
                'order' => 7,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 0,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'nullable' => 1,
                'can_create_search_choice' => 0,
                'created_at' => '2018-01-22 22:35:09',
                'updated_at' => '2018-01-22 22:35:09',
            ),
            array (
                'type' => 1,
                'name' => 'Alt Text',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'alt_text',
                'virtual_name' => NULL,
                'tooltip_text' => 'The alt text of the image.',
                'validation_rules' => NULL,
                'module_id' => 4,
                'order' => 8,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 0,
                'virtual' => 0,
                'lazy_loading' => 0,
                'default' => NULL,
                'nullable' => 1,
                'can_create_search_choice' => 0,
                'created_at' => '2018-01-22 22:35:09',
                'updated_at' => '2018-01-22 22:35:09',
            ),
            array (
                'type' => 8,
                'name' => 'File Tags',
                'related_module' => 7,
                'relation_name' => 'tags',
                'pivot_table' => NULL,
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'Assigned file tags',
                'validation_rules' => 'exists:file_tags,id',
                'module_id' => 4,
                'order' => 9,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 1,
                'default' => NULL,
                'nullable' => 0,
                'can_create_search_choice' => 1,
                'created_at' => '2016-10-07 07:38:15',
                'updated_at' => '2016-10-07 07:38:15',
            ),
        ));
    }
}
