<?php

use Illuminate\Database\Seeder;

class InitialCoreWidgetsModuleSeeder extends Seeder
{
    public function run()
    {
        // Modules
        \DB::table('modules')->insert(array (
            0 =>
            array (
                'id' => 8,
                'category' => 0,
                'type' => 'sortable',
                'name' => 'Widgets',
                'model_name' => 'Widgets',
                'table_name' => 'widgets',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => NULL,
                'anchor_html' => NULL,
                'icon' => 'fa fa-square',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'created_at' => '2018-01-10 22:23:31',
                'updated_at' => '2018-01-11 08:18:51',
            ),
        ));

        // Fields
        \DB::table('fields')->insert(array (
            array (
                'type' => 1,
                'name' => 'Module',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'module',
                'virtual_name' => NULL,
                'tooltip_text' => 'Data source module.',
                'validation_rules' => 'nullable',
                'module_id' => 8,
                'order' => 0,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 0,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2018-01-10 22:23:31',
                'updated_at' => '2018-01-11 08:18:51',
            ),

            array (
                'type' => 1,
                'name' => 'Heading Text',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'heading',
                'virtual_name' => NULL,
                'tooltip_text' => 'The text which will appear in widget heading.',
                'validation_rules' => 'nullable',
                'module_id' => 8,
                'order' => 1,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 0,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2018-01-10 22:23:31',
                'updated_at' => '2018-01-11 08:18:51',
            ),

            array (
                'type' => 1,
                'name' => 'Icon',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'icon',
                'virtual_name' => NULL,
                'tooltip_text' => 'The icon which will appear in widget heading.',
                'validation_rules' => 'nullable',
                'module_id' => 8,
                'order' => 2,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 0,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => 'fa fa-circle',
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2018-01-10 22:23:31',
                'updated_at' => '2018-01-11 08:18:51',
            ),

            array (
                'type' => 1,
                'name' => 'Theme',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'theme',
                'virtual_name' => NULL,
                'tooltip_text' => 'Widget theme.',
                'validation_rules' => 'required|nullable',
                'module_id' => 8,
                'order' => 3,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 0,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => 'panel-primary',
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2018-01-10 22:23:31',
                'updated_at' => '2018-01-11 08:18:51',
            ),

            array (
                'type' => 1,
                'name' => 'Data Refresh Interval',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'refresh_interval',
                'virtual_name' => NULL,
                'tooltip_text' => 'Widget data refresh interval.',
                'validation_rules' => 'integer|nullable',
                'module_id' => 8,
                'order' => 4,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 0,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => '5000',
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2018-01-10 22:23:31',
                'updated_at' => '2018-01-11 08:18:51',
            ),

            array (
                'type' => 1,
                'name' => 'Type',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'type',
                'virtual_name' => NULL,
                'tooltip_text' => 'Widget Type',
                'validation_rules' => 'required',
                'module_id' => 8,
                'order' => 6,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 0,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2018-01-10 22:23:31',
                'updated_at' => '2018-01-11 08:18:51',
            ),

            array (
                'type' => 2,
                'name' => 'Meta Data',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'meta_data',
                'virtual_name' => NULL,
                'tooltip_text' => 'Data specific to seleted widget type.',
                'validation_rules' => 'nullable',
                'module_id' => 8,
                'order' => 7,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 0,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => NULL,
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 1,
                'indexed' => 0,
                'created_at' => '2018-01-10 22:23:31',
                'updated_at' => '2018-01-11 08:18:51',
            ),

            array (
                'type' => 4,
                'name' => 'Private',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'private',
                'virtual_name' => NULL,
                'tooltip_text' => NULL,
                'validation_rules' => NULL,
                'module_id' => 8,
                'order' => 5,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 0,
                'virtual' => 0,
                'lazy_loading' => 0,
                'can_create_search_choice' => 0,
                'is_default_search_choice' => 0,
                'active_entry_filter' => NULL,
                'flatten_to_optgroups' => 0,
                'default' => '0',
                'local_key' => NULL,
                'foreign_key' => NULL,
                'nullable' => 0,
                'indexed' => 0,
                'created_at' => '2018-01-10 22:23:56',
                'updated_at' => '2018-01-11 08:18:51',
            ),
        ));
    }
}
