<?php

use Illuminate\Database\Seeder;

class InitialCoreUsersModuleSeeder extends Seeder
{
    public function run()
    {
        // Modules
        \DB::table('modules')->insert(array (
            0 =>
            array (
                'id' => 1,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Users',
                'model_name' => 'User',
                'table_name' => 'users',
                'anchor_text' => '{{first_name}} {{last_name}}',
                'icon' => 'fa fa-users',
                'reporting' => true,
                'lazy_loading' => 0,
                'is_system' => true,
                'created_at' => '2016-04-01 09:17:48',
                'updated_at' => '2016-04-01 11:29:51',
            )
        ));

        // Fields
        \DB::table('fields')->insert(array (
            0 =>
            array (
                'type' => 1,
                'name' => 'Email',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'email',
                'virtual_name' => NULL,
                'tooltip_text' => 'User email will be used as a username. If required, account confirmation will be sent to this email. Email will also be used in the event of recovering a lost password.',
                'validation_rules' => 'required|unique:users,email|max:255',
                'module_id' => 1,
                'order' => 0,
                'editable' => true,
                'disabled' => false,
                'hidden' => false,
                'is_system' => 1,
                'virtual' => false,
                'lazy_loading' => 0,
                'nullable' => 0,
                'created_at' => '2016-04-01 09:17:48',
                'updated_at' => '2016-04-01 09:17:48',
            ),
            1 =>
            array (
                'type' => 9,
                'name' => 'Password',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'password',
                'virtual_name' => NULL,
                'tooltip_text' => 'User Password.',
                'validation_rules' => 'required|min:8|regex:/^.*(?=.{3,})(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[\d\X])(?=.*[!$#%]).*$/',
                'module_id' => 1,
                'order' => 1,
                'editable' => true,
                'disabled' => false,
                'hidden' => false,
                'is_system' => 1,
                'virtual' => false,
                'lazy_loading' => 0,
                'nullable' => 0,
                'created_at' => '2016-04-01 09:17:48',
                'updated_at' => '2016-04-01 09:17:48',
            ),
            2 =>
            array (
                'type' => 1,
                'name' => 'First Name',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'first_name',
                'virtual_name' => NULL,
                'tooltip_text' => 'User first name.',
                'validation_rules' => 'required|string|min:2',
                'module_id' => 1,
                'order' => 2,
                'editable' => true,
                'disabled' => false,
                'hidden' => false,
                'is_system' => 1,
                'virtual' => false,
                'lazy_loading' => 0,
                'nullable' => 0,
                'created_at' => '2016-04-01 09:17:48',
                'updated_at' => '2016-04-01 09:17:48',
            ),
            3 =>
            array (
                'type' => 1,
                'name' => 'Last Name',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'last_name',
                'virtual_name' => NULL,
                'tooltip_text' => 'User last name.',
                'validation_rules' => 'required|string|min:2',
                'module_id' => 1,
                'order' => 3,
                'editable' => true,
                'disabled' => false,
                'hidden' => false,
                'is_system' => 1,
                'virtual' => false,
                'lazy_loading' => 0,
                'nullable' => 0,
                'created_at' => '2016-04-01 09:17:48',
                'updated_at' => '2016-04-01 09:17:48',
            ),
            4 =>
            array (
                'type' => 1,
                'name' => 'Confirmation Code',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'confirmation_code',
                'virtual_name' => NULL,
                'tooltip_text' => 'User confirmation code.',
                'validation_rules' => 'string',
                'module_id' => 1,
                'order' => 4,
                'editable' => false,
                'disabled' => true,
                'hidden' => true,
                'is_system' => true,
                'virtual' => false,
                'lazy_loading' => 0,
                'nullable' => 1,
                'created_at' => '2016-04-01 09:17:48',
                'updated_at' => '2016-04-01 09:17:48',
            ),
            5 =>
            array (
                'type' => 4,
                'name' => 'Confirmed',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'confirmed',
                'virtual_name' => NULL,
                'tooltip_text' => 'User confirmation status.',
                'validation_rules' => 'boolean',
                'module_id' => 1,
                'order' => 5,
                'editable' => false,
                'disabled' => true,
                'hidden' => true,
                'is_system' => true,
                'virtual' => false,
                'lazy_loading' => 0,
                'nullable' => 1,
                'created_at' => '2016-04-01 09:17:48',
                'updated_at' => '2016-04-01 09:17:48',
            ),
            6 =>
            array (
                'type' => 8,
                'name' => 'Roles',
                'related_module' => 5,
                'relation_name' => 'roles',
                'pivot_table' => 'user_has_roles',
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'Roles which are assigned to this user.',
                'validation_rules' => NULL,
                'module_id' => 1,
                'order' => 6,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'nullable' => 1,
                'created_at' => '2016-09-05 12:50:26',
                'updated_at' => '2016-09-05 12:50:26',
            ),
            7 =>
            array (
                'type' => 24,
                'name' => 'Permissions',
                'related_module' => 6,
                'relation_name' => 'permissions',
                'pivot_table' => 'user_has_permissions',
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'Permissions which are assigned to this user.',
                'validation_rules' => NULL,
                'module_id' => 1,
                'order' => 7,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'nullable' => 1,
                'created_at' => '2016-09-05 12:50:26',
                'updated_at' => '2016-09-05 12:50:26',
            ),
            8 =>
            array (
                'type' => 15,
                'name' => 'Profile Image',
                'related_module' => 4,
                'relation_name' => 'profile_image',
                'pivot_table' => NULL,
                'column_name' => NULL,
                'virtual_name' => NULL,
                'tooltip_text' => 'This is the user profile image.',
                'validation_rules' => NULL,
                'module_id' => 1,
                'order' => 8,
                'editable' => 1,
                'disabled' => 0,
                'hidden' => 0,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'nullable' => 1,
                'created_at' => '2016-09-01 06:44:16',
                'updated_at' => '2016-09-01 06:44:16',
            ),
            9 =>
            array (
                'type' => 12,
                'name' => 'Password Creation Date',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'password_created_at',
                'virtual_name' => NULL,
                'tooltip_text' => 'Date when the last password was created.',
                'validation_rules' => NULL,
                'module_id' => 1,
                'order' => 9,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => true,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'nullable' => 1,
                'created_at' => '2016-09-29 12:55:25',
                'updated_at' => '2016-09-29 12:55:25',
            ),
            10 =>
            array (
                'type' => 12,
                'name' => 'Deletion Date',
                'related_module' => NULL,
                'relation_name' => NULL,
                'pivot_table' => NULL,
                'column_name' => 'deleted_at',
                'virtual_name' => NULL,
                'tooltip_text' => 'Date when the entry was deleted.',
                'validation_rules' => NULL,
                'module_id' => 1,
                'order' => 10,
                'editable' => 0,
                'disabled' => 1,
                'hidden' => true,
                'is_system' => 1,
                'virtual' => 0,
                'lazy_loading' => 0,
                'nullable' => 1,
                'created_at' => '2016-09-29 12:55:25',
                'updated_at' => '2016-09-29 12:55:25',
            ),
        ));
    }
}
