version: '2'
services:
    photon:
      build:
        context: .
        args:
          - ENABLE_OPCACHE=false
          - INSTALL_XDEBUG=true
      env_file: .env
      container_name: photon
      volumes:
        - ./app:/var/www/app
        - ./config:/var/www/config
        - ./database:/var/www/database
        - ./resources:/var/www/resources
        - ./routes:/var/www/routes
      ports:
        - "80:80"
      links:
        - "mysql:mysql"

    mysql:
      image: mysql
      container_name: mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_DATABASE=photon
        - MYSQL_USER=photon
        - MYSQL_PASSWORD=photon
        - MYSQL_ROOT_PASSWORD=photon
      volumes:
        - ./data:/var/lib/mysql